import { ElementProperties } from '@/types';

export async function exportElementToPdf(element: ElementProperties): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  const html2canvas = (await import('html2canvas')).default;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  const elementContainer = document.createElement('div');
  elementContainer.style.cssText = `
    width: ${contentWidth * 3.78}px;
    padding: 20px;
    font-family: Arial, sans-serif;
    background: #ffffff;
    color: #1a1a2e;
    position: fixed;
    left: -9999px;
    top: 0;
  `;

  elementContainer.innerHTML = `
    <div style="display:flex;align-items:center;gap:16px;margin-bottom:12px;padding-bottom:12px;border-bottom:2px solid #333;">
      <div style="font-size:48px;font-weight:700;">${element.atomicNumber}</div>
      <div>
        <div style="font-size:42px;font-weight:700;">${element.symbol}</div>
        <div style="font-size:24px;color:#666;">${element.name}</div>
      </div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:12px;">
      <div><strong>Atomic Weight:</strong> ${element.atomicMass}</div>
      <div><strong>Group:</strong> ${element.group ?? 'N/A'}</div>
      <div><strong>Period:</strong> ${element.period}</div>
      <div><strong>Block:</strong> ${element.block.toUpperCase()}</div>
      <div><strong>Category:</strong> ${element.categoryName}</div>
      <div><strong>Electron Config:</strong> ${element.electronConfiguration}</div>
      <div><strong>Phase:</strong> ${element.phase}</div>
      <div><strong>Density:</strong> ${element.density ? `${element.density} g/cm³` : 'N/A'}</div>
      <div><strong>Melting Point:</strong> ${element.meltingPoint ? `${element.meltingPoint} K` : 'N/A'}</div>
      <div><strong>Boiling Point:</strong> ${element.boilingPoint ? `${element.boilingPoint} K` : 'N/A'}</div>
      <div><strong>Electronegativity:</strong> ${element.electronegativity ?? 'N/A'}</div>
      <div><strong>Ionization Energy:</strong> ${element.ionizationEnergy ? `${element.ionizationEnergy} eV` : 'N/A'}</div>
    </div>
    <div style="margin-top:16px;font-size:11px;color:#888;border-top:1px solid #ddd;padding-top:8px;">
      Generated by Periodic Elements Explorer
    </div>
  `;

  document.body.appendChild(elementContainer);

  try {
    const canvas = await html2canvas(elementContainer, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });

    const imgData = canvas.toDataURL('image/png');
    const imgWidth = contentWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    doc.addImage(imgData, 'PNG', margin, margin, imgWidth, imgHeight);
    doc.save(`${element.symbol}_${element.name}.pdf`);
  } finally {
    document.body.removeChild(elementContainer);
  }
}
